title: CompSci Blogs
description: "August 2023 to June 2024"
owner_name: Theo Huntalas
github_username: TheoH32
baseurl: "/csa_blog"
remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true

inputs:
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
    default: ${{ secrets.USER_API_KEY }}

run:
  using: 'node12'
  main: 'webpack.config.js'

jobs:
  steps:
    run:
      echo ${{ inputs.GITHUB_TOKEN}}